Chuck
tomsloni/kodilla-ajax pull request #1
Opened 2016-12-20 21:36 UTC by tomsloni

2016-12-20 22:53 UTC, zdolny requested changes

2016-12-20 22:53 UTC, zdolny commented on chuck_jquery.html
> +		<script type='text/javascript' src='chuck.js'></script>
nie ten plik

2016-12-20 22:53 UTC, zdolny commented on chuck_jquery.js
> +			$paragraph.text(res.value.joke)
brak srednika

2016-12-20 22:53 UTC, zdolny commented on chuck_jquery.js
> +$(function(){ getJoke(); });
najsensowniej byloby cala zawartosc pliku wrzucic do `$(function(){`

2016-12-21 00:46 UTC, tomsloni commented
Poprawione

2016-12-21 01:21 UTC, zdolny reviewed
brawo :) no i przetestowales, bo dodales jQuery :) 👍

2016-12-21 01:21 UTC, merged