Greatquotes
tomsloni/kodilla-ajax pull request #3
Opened 2016-12-20 21:37 UTC by tomsloni

2016-12-20 23:01 UTC, zdolny requested changes

2016-12-20 23:01 UTC, zdolny commented on greatquotes.html
> +		<link rel='stylesheet' type='text/css' href='greatquotes.css'>
Twoj css jako ostatni

2016-12-20 23:01 UTC, zdolny commented on greatquotes.js
> +		$('#tweet').attr('href', tweet)
brak srednika

2016-12-20 23:01 UTC, zdolny commented on greatquotes.js
> +$(function(){ getQuote(); });
calosc w ta funkcje

2016-12-20 23:01 UTC, zdolny commented on greatquotes.js
> +var $button = $('#generate').click(function() {
obczaj funkcje jQuery o nazwie `.trigger()`

2016-12-21 01:33 UTC, tomsloni commented
poprawione

2016-12-23 17:31 UTC, zdolny commented on greatquotes.html
>  		<header>
chodzilo mi o kolejnosc w obrebie css

2016-12-23 17:32 UTC, zdolny commented on greatquotes.js
> -	$('#generate').trigger('click');
fajnie, ze poznales nowa funkcje, ale niespodzianka - bez tego tez dziala :)

2016-12-23 17:32 UTC, zdolny approved these changes

2016-12-23 17:33 UTC, merged